### ISSUE TITLE
Genesis Device 2010

### ISSUE THREAD

**Issue by gonmon3** [seriva/GenesisDevice#6]
Do you have a backup, since I was about to update it to work on a newer Lazarus and you killed it? It had the editor and barbarian demo, I would have liked to mess with.

**Comment by gonmon3** [comment]
Turns out I did have backups of the old files, but had to get them from another disk.

**Comment by seriva** [comment]
Hey man! I am currently working on integrating the 2007 and 2010 versions into a single codebase with 2007 as base. So you can expect the 2010 features to show up there in the next few weeks/months depending on how much time I have. Feel free to reach out if you miss something and I can share it.

**Comment by gonmon3** [comment]
Yeah, much appreciated and looking forward to its revival.

**Comment by seriva** [comment]
> Yeah, much appreciated and looking forward to its revival.

Should be fun:) Keep me posted what your are working on:) Always interested to see what people use your creations for:)

**Comment by gonmon3** [comment]
Most certainly. I currently have a local Fossil repo for my project, due to my game data being closed-source (for the time being), but I'll put the details and source up when the asset creation and tech is further along, which could deviate from the original tech.
